### ISSUE TITLE
Jarvis API

### ISSUE THREAD

**Issue by Mousseron** [alexylem/jarvis-api#17]
Bonjour , 
Tous d'abord merci pour le travail réalisé , un grand bravo . 
Concernant mon problème je pense avoir lu pas mal , peut être les ai-je mal compris, mais je n'arrive pas à le solutionner .
Mon problème concerne Jarvis API 
lors que je lance un simple requete JSON vers mon pi 2 depuis mon navigateur  je me retrouve ex: http://ip:8080/?say=jarvis  
Je me retrouve avec 
"error": "No JSON object could be decoded" 

Idem quand je test depuis mon téléphone androïde en suivant le  tuto https://www.openjarvis.com/content/voice-control-from-android-device
le mot est bien reconnu mais concernant la commande je me retrouve avec la même erreur 
"error": "No JSON object could be decoded"
j'ai désactiver tous le plugins sauf biensur le JARVIS API que j'ai tenté de réactive et reinstaller . 
En terme de ressources tous ce passe bien d'un point de vu CPU et RAM rien a signaler 
Ma SD est une 32 gio ultra samsung donc je ne pense pas que ce soit un frein 

je vous joint les dernières lignes de log 

mercredi 12 juillet 2017, 11:01:12 (UTC+0200) jarvis: Waiting to hear 'jarvis'
mercredi 12 juillet 2017, 11:01:42 (UTC+0200) Can't get device info: No such device
mercredi 12 juillet 2017, 11:01:42 (UTC+0200) {"debug":"DEBUG: start_speaking hook"},{"answer":"Je n'ai pas compris: service"},{"debug":"DEBUG: stop_speaking hook"},{"debug":"*OUI*            *NON*|*PAS*"}]
mercredi 12 juillet 2017, 11:01:42 (UTC+0200) Mustapha: 1.0.97.62 - - [12/Jul/2017 11:01:42] "POST / HTTP/1.1" 400 -
mercredi 12 juillet 2017, 11:02:03 (UTC+0200) Can't get device info: No such device
mercredi 12 juillet 2017, 11:02:03 (UTC+0200) {"debug":"DEBUG: start_speaking hook"},{"answer":"Je n'ai pas compris: Bonjour"},{"debug":"DEBUG: stop_speaking hook"},{"debug":"*OUI*            *NON*|*PAS*"}]
mercredi 12 juillet 2017, 11:02:03 (UTC+0200) 1.0.97.62 - - [12/Jul/2017 11:02:03] "POST / HTTP/1.1" 400 -

Merci d'avance pour vos Lumières .

**Comment by Oliv4945** [comment]
Bonjour,

Tu es le 2ème cette semaine avec ce soucis mais je n'arrive pas à le reproduire. Que donne un log complet avec `jarvis -nv` ?
Sur le rPi, si tu fais `curl http://localhost:8080/?order=test` ?
Dans le répertoire `jarvis/plugins_enabled/jarvis-api/` que donne la commande `git log -4` ?

**Comment by Mousseron** [comment]
Bonsoir oliv
suite au curl test voici les deux lignes qui apparaisent dans le log jarvis.log	

mercredi 12 juillet 2017, 22:25:55 (UTC+0200) Can't get device info: No such device
mercredi 12 juillet 2017, 22:25:56 (UTC+0200) {"answer":"Ca fonctionne!"}]

rien de bien parlant 

Voici le log de la partie plugins
pi@raspberrypi:~/jarvis/plugins_enabled/jarvis-api $ git log -4
commit f1cbf5c44cff257e46090805cfde29e26a6dbc56
Author: Alexandre Mély <alexandre.mely@gmail.com>
Date:   Sat May 13 13:53:03 2017 +0200

    use symlink

commit 6ec285fd722cfc1119733b5a8f94a6b9bd4a9928
Author: Alexandre Mély <alexandre.mely@gmail.com>
Date:   Thu May 11 23:21:09 2017 +0200

    #15 support case variation of booleans

commit aa54332f4520aafe67fc890b5480e87ec38c2d90
Author: Alexandre Mély <alexandre.mely@gmail.com>
Date:   Thu May 11 21:22:45 2017 +0200

    fixed #15 wrong boolean interpretation

commit 6b106b5f20492fce0520af14869661b019d3250c
Author: Alexandre Mély <alexandre.mely@gmail.com>
Date:   Sat Apr 29 15:10:33 2017 +0200
alexylem/jarvis#564 "answer" instead of trigger in JSON reply

Restant à dispo .

**Comment by Oliv4945** [comment]
@Mousseron : il manque `jarvis -nv`, lorsque tu lances la commande dans le navigateur pour voir ;-)

Sinon le curl est parlant : ça fonctionne en local ! Est-ce que tu as un autre pc sous linux ou rPi pour tester `curl http://ipDeJarvis:8080/?order=test` ?
Au cas où est-ce que tu pourrais essayer aussi `curl http://localhost:8080/?say=test`

**Comment by Mousseron** [comment]
@Oliv4945 pour le poste en linux je te fais ça demain le temps de monter la vm . 
Par contre pour bien comprendre & ne pas te faire répéter encore une fois
 
1) jarvis -nv je le lance depuis le shell 
2) ensuite je lance ma commande curl 
3) je kill jarvis avec un ctrl+c 
4) je vais chercher le résultat dans le jarvis.log 
car si c'est ca c'est bien ce que j'ai fais a moins d'avoir oublié une étape .

**Comment by Oliv4945** [comment]
Presque :)
mieux vaut prendre le résultat de la console. D'ailleurs si tu peux ajouter `-v` à curl :)

Sinon sous Windows tu peux mettre Wget : http://gnuwin32.sourceforge.net/packages/wget.htm

**Comment by mikevador02** [comment]
Bonjour,

J'ai un problème identique de retour json sur une fresh jessie 

La commande elle fonctionne j'ai bien le son, ou l'ordre donné qui passe.


Depuis un Pi je lance la commande suivante pour executer un say:

 curl -v "http://192.168.1.7:8080?say=Hello%20World"
* Rebuilt URL to: http://192.168.1.7:8080/?say=Hello%20World
* Hostname was NOT found in DNS cache
*   Trying 192.168.1.7...
* Connected to 192.168.1.7 (192.168.1.7) port 8080 (#0)
> GET /?say=Hello%20World HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 192.168.1.7:8080
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad Request
< Server: BaseHTTP/0.3 Python/2.7.9
< Date: Sat, 11 Nov 2017 12:41:40 GMT
< Access-Control-Allow-Origin: *
< Content-type: application/json
<
* Closing connection 0
{"error": "No JSON object could be decoded"}





Et sur mon pi jarvis j'ai qui execute et lit le say:

DEBUG: using cache /dev/shm/hello_world.mp3
192.168.1.31 - - [11/Nov/2017 12:44:34] "GET /?say=Hello%20World HTTP/1.1" 400 -
ERROR: No JSON object could be decoded


Merci de votre aide.

**Comment by brendacomagio** [comment]
Bonjour,

régulièrement quand je lance une commande listen via l'url jarvis plante (ca fonctionne 2 ou 3 fois et après crash) voila ce que me donne le -nv :

DEBUG: start_speaking hook ""
utils/timeout.sh 10 python  recorders/snowboy/main.py  -1 /dev/shm/jarvis-record.wav
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "recorders/snowboy/main.py", line 60, in <module>
    trigger_ticks=trigger_ticks )
  File "/home/pi/jarvis/recorders/snowboy/wavget.py", line 78, in __init__
    stream_callback=audio_callback)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9996] Invalid input device (no default output device)
ERROR: rec command failed
HELP: retry in troubleshooting mode for more details

est ce que quelqu'un a une idee ?

merci de votre aide
